service: sls-middy-error-handling
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

constructs:
  profile:
    type: storage

functions:
  hello:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get
    environment:
      MIDDY_PROFILER_S3_BUCKET_NAME: ${construct:profile.bucketName}

plugins:
  - serverless-lift
