service: sls-middy-error-handling
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

functions:
  hello:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get
